package com.sayanx.composenote.model

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey
import java.util.UUID

@Entity(tableName = "notes_tbl") // creating a data-table(entity) in the data-base
data class Note(
    @PrimaryKey(autoGenerate = false) //as id is generated by UUID
    val id: UUID = UUID.randomUUID(),

    @ColumnInfo(name = "note_title")
    val title: String?,

    @ColumnInfo(name = "note_description")
    val description: String?
)

